// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function parseRoute(path) {
  let parts = path.split("/").filter(p => p !== "");
  let len = parts.length;
  if (len >= 5) {
    return "Home";
  }
  switch (len) {
    case 1 :
      let match = parts[0];
      if (match === "groups") {
        return "Groups";
      } else {
        return "Home";
      }
    case 2 :
      let match$1 = parts[0];
      if (match$1 !== "groups") {
        return "Home";
      }
      let groupName = parts[1];
      return {
        TAG: "GroupView",
        _0: groupName
      };
    case 0 :
    case 3 :
      return "Home";
    case 4 :
      let match$2 = parts[0];
      if (match$2 !== "groups") {
        return "Home";
      }
      let groupName$1 = parts[1];
      let match$3 = parts[2];
      if (match$3 !== "article") {
        return "Home";
      }
      let articleId = parts[3];
      return {
        TAG: "ArticleView",
        _0: groupName$1,
        _1: articleId
      };
  }
}

function routeToPath(route) {
  if (typeof route !== "object") {
    if (route === "Home") {
      return "/";
    } else {
      return "/groups";
    }
  } else if (route.TAG === "GroupView") {
    return `/groups/` + route._0;
  } else {
    return `/groups/` + route._0 + `/article/` + route._1;
  }
}

function push(route) {
  routeToPath(route);
  ((window.history.pushState({}, "", path)));
  return (window.dispatchEvent(new PopStateEvent('popstate')));
}

function replace(route) {
  routeToPath(route);
  return (window.history.replaceState({}, "", path));
}

function getCurrentRoute() {
  return parseRoute(window.location.pathname);
}

function useRouter() {
  let match = React.useState(() => getCurrentRoute());
  React.useEffect(() => {
    ((window.addEventListener('popstate', listener)));
    return () => ((window.removeEventListener('popstate', listener)));
  }, []);
  return [
    match[0],
    push
  ];
}

export {
  parseRoute,
  routeToPath,
  push,
  replace,
  getCurrentRoute,
  useRouter,
}
/* react Not a pure module */
